### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [codyromano/warren-buffett-scorecard#1]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/codyromano/warren-buffett-scorecard/blob/master/package.json#L37

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by codyromano** [comment]
Good catch, Daniel! Thanks
